### ISSUE TITLE
Chrome: "This extension contains malware" and extension removed from store?

### ISSUE THREAD

**Issue by sebastianstucke87** [cansinacarer/Doodle-Blocker-for-Google#2]
![2023-11-27 10_17_05-Window](https://github.com/cansinacarer/Doodle-Blocker-for-Google/assets/47354551/ba9817dd-26e2-473d-9319-fa4dd078e8c0)

**404**: https://chrome.google.com/webstore/detail/doodle-blocker-for-google/jfcifhfgpkjakpfmilfkfjnfabgmhpnl

**Comment by cansinacarer** [comment]
Hi, This extension was recently bought by [Limitless Media](https://www.limitlessmediaextension.com/). The extension listed in the Chrome store no longer follows the code in this repository.

Feel free to use the code in this repository as you wish.
